-- Seed Data (Matches MockData)

-- Clear existing products to avoid duplicates during multiple seeds
DELETE FROM public.products;

-- LIFESTYLE
INSERT INTO public.products (id, name, category, price, image, description, specs) VALUES
('cf-wallet-01', 'Minimalist Cardholder', 'Lifestyle', 4999, 'https://images.unsplash.com/photo-1579014134953-1580d7f123f3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibGFjayUyMGxlYXRoZXIlMjB3YWxsZXR8ZW58MXx8fHwxNzgwNjgxNDQzfDA&ixlib=rb-4.1.0&q=80&w=1080', 'Aerospace-grade carbon fiber woven into a sleek, RFID-blocking silhouette. Holds up to 6 cards.', ARRAY['Weight: 14g', 'Thickness: 4mm', 'Finish: Matte', 'Material: 3K Twill Carbon Fiber']),
('cf-watch-box', 'Collector''s Timepiece Case', 'Lifestyle', 12999, 'https://images.unsplash.com/photo-1616928231359-fc8b7e244c3b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibGFjayUyMG1pbmltYWxpc3QlMjB3YXRjaHxlbnwxfHx8fDE3ODA2ODE0NDN8MA&ixlib=rb-4.1.0&q=80&w=1080', 'Store your prized possessions in a fortress of forged carbon. Alcantara lined interior.', ARRAY['Capacity: 3 Watches', 'Interior: Black Alcantara', 'Hinges: Machined Aluminum', 'Material: Forged Carbon Fiber']),
('cf-keychain-01', 'Forged Carabiner Keychain', 'Lifestyle', 2499, 'https://images.unsplash.com/photo-1590740051939-2ceee281179a?auto=format&fit=crop&q=80&w=1000', 'Ultra-lightweight EDC carabiner crafted from chopped carbon fiber tows. Unique marbled pattern.', ARRAY['Weight: 8g', 'Load Capacity: 25kg', 'Finish: Gloss', 'Material: Forged Carbon']),
('cf-cigar-tube', 'Executive Cigar Tube', 'Lifestyle', 5999, 'https://images.unsplash.com/photo-1623945415758-204127041697?auto=format&fit=crop&q=80&w=1000', 'Maintain perfect humidity. Crush-proof carbon fiber construction with CNC machined titanium end caps.', ARRAY['Length: 170mm', 'Diameter: 22mm', 'Seal: O-Ring', 'Material: 3K Twill']),
('cf-pen-01', 'Tactical Bolt-Action Pen', 'Lifestyle', 8999, 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?auto=format&fit=crop&q=80&w=1000', 'Smooth writing meets rugged durability. Real carbon fiber barrel wrapped around a brass inner tube.', ARRAY['Ink: Fisher Space', 'Mechanism: Bolt Action', 'Weight: 22g', 'Trim: Titanium']);

-- ACCESSORIES
INSERT INTO public.products (id, name, category, price, image, description, specs) VALUES
('cf-case-14', 'iPhone 15 Pro Aramid Case', 'Accessories', 3499, 'https://images.unsplash.com/photo-1637004732258-4b792ce8f474?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibGFjayUyMGNhcmJvbiUyMGZpYmVyJTIwdGV4dHVyZXxlbnwxfHx8fDE3ODA2ODE0NDN8MA&ixlib=rb-4.1.0&q=80&w=1080', 'Snap-on protection crafted from 100% genuine aramid fiber. Zero signal interference. MagSafe compatible.', ARRAY['Weight: 12g', 'Thickness: 0.6mm', 'MagSafe: Yes', 'Material: Aramid Fiber']),
('cf-s24-case', 'Galaxy S24 Ultra Forged Case', 'Accessories', 3499, 'https://images.unsplash.com/photo-1541411032338-715bb179e8a7?auto=format&fit=crop&q=80&w=1000', 'Precision molded forged carbon case with shock-absorbing TPU bumpers.', ARRAY['Weight: 15g', 'Drop Protection: 6ft', 'Wireless Charging: Yes', 'Material: Forged Carbon + TPU']),
('cf-airpods-pro', 'AirPods Pro 2 Armor', 'Accessories', 2999, 'https://images.unsplash.com/photo-1588156979401-447551069680?auto=format&fit=crop&q=80&w=1000', 'Two-piece hard shell case made from real 3K twill carbon fiber. LED visible.', ARRAY['Thickness: 0.8mm', 'Fit: Snap-on', 'Lanyard Loop: Yes', 'Material: 3K Twill']),
('cf-macbook-sleeve', 'MacBook Pro 14 Sleeve', 'Accessories', 7499, 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=1000', 'Flexible carbon fiber leather alternative. Water-resistant and incredibly durable.', ARRAY['Compatibility: 14-inch laptops', 'Interior: Microfiber', 'Closure: Magnetic', 'Material: Carbon Fiber Leather']);

-- AUTO
INSERT INTO public.products (id, name, category, price, image, description, specs) VALUES
('cf-spoiler-m3', 'BMW M3 G80 Rear Spoiler', 'Auto', 45000, 'https://images.unsplash.com/photo-1669882571612-4a9c7822cd4c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBibGFjayUyMHNwb3J0cyUyMGNhciUyMGRldGFpbHN8ZW58MXx8fHwxNzgwNjgxNDQzfDA&ixlib=rb-4.1.0&q=80&w=1080', 'Aggressive styling meets aerodynamic downforce. Pre-preg carbon fiber baked in an autoclave for maximum strength.', ARRAY['Weight: 1.2kg', 'Weave: 2x2 Twill', 'Fitment: BMW G80/G82', 'Coating: UV-Resistant Clear Coat']),
('cf-mirror-m', 'M-Style Mirror Caps', 'Auto', 22000, 'https://images.unsplash.com/photo-1600712242805-5f78671b24da?auto=format&fit=crop&q=80&w=1000', 'Direct replacement mirror covers. Not overlays. Fully molded carbon fiber for perfect fitment.', ARRAY['Install: Direct Replacement', 'Weave: 2x2 Twill', 'Fitment: BMW F30/F32', 'Finish: High Gloss']),
('cf-steering-wheel', 'Custom Carbon Steering Wheel', 'Auto', 85000, 'https://images.unsplash.com/photo-1605514681602-de549bd9b1dc?auto=format&fit=crop&q=80&w=1000', 'Reshaped core with carbon fiber top/bottom and perforated leather grips. LED shift lights available.', ARRAY['Grips: Perforated Leather', 'Shape: Flat Bottom', 'Stitching: M-Tri Color', 'Material: Carbon Fiber Core']),
('cf-paddle-shifters', 'Extended Paddle Shifters', 'Auto', 12500, 'https://images.unsplash.com/photo-1620912165080-60b6d27cb1ba?auto=format&fit=crop&q=80&w=1000', 'Enhance your shifting experience with extended reach and tactile feedback.', ARRAY['Install: Bolt-on', 'Length: +40mm', 'Feedback: Tactile click', 'Material: Dry Carbon']),
('cf-diffuser-c63', 'AMG C63 Rear Diffuser', 'Auto', 68000, 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&q=80&w=1000', 'Enhance rear airflow and downforce. Aggressive 4-fin design with perfectly aligned weave.', ARRAY['Fins: 4', 'Fitment: W205 C63', 'Install: Bumper removal required', 'Weave: 2x2 Twill']),
('cf-exhaust-tips', 'Akrapovic Style Exhaust Tips', 'Auto', 18000, 'https://images.unsplash.com/photo-1598453303642-1e96a233513d?auto=format&fit=crop&q=80&w=1000', 'Stainless steel inner core with dry carbon fiber sleeve. Heat resistant.', ARRAY['Inlet: 63mm', 'Outlet: 89mm', 'Core: 304 Stainless', 'Sleeve: Dry Carbon']);
